name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    environment: secrets   # <-- match the Environment that holds the secrets

    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      # sanity check the secret shape so we fail fast with a clear error
      - name: Validate AZURE_CREDENTIALS secret
        shell: bash
        run: |
          jq -re 'has("clientId") and has("clientSecret") and has("tenantId") and has("subscriptionId")' \
            <<< '${{ secrets.AZURE_CREDENTIALS }}' >/dev/null || {
              echo "::error::AZURE_CREDENTIALS must be a JSON with clientId, clientSecret, tenantId, subscriptionId"; exit 1; }

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Derive ACR name
        run: echo "ACR_NAME=${ACR_LOGIN_SERVER%%.*}" >> "$GITHUB_ENV"

      - name: Login to ACR
        run: az acr login --name "$ACR_NAME"

      - name: Build & Push frontend image
        run: |
          IMAGE="${ACR_LOGIN_SERVER}/frontend"
          docker build -t "${IMAGE}:latest" -t "${IMAGE}:${IMAGE_TAG}" ./frontend
          docker push "${IMAGE}:latest"
          docker push "${IMAGE}:${IMAGE_TAG}"

      - name: Logout from Azure
        if: always()
        run: az logout || true
